# Generated by Django 5.2 on 2025-04-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tags',
            field=models.CharField(max_length=255),
        ),
    ]
